// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $api_data_armies_for_user from "./routes/api/data/armies-for-user.ts";
import * as $api_data_armies_aid_ from "./routes/api/data/armies/[aid].ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_signup from "./routes/api/signup.ts";
import * as $export from "./routes/export.tsx";
import * as $hammer from "./routes/hammer.tsx";
import * as $hello from "./routes/hello.tsx";
import * as $index from "./routes/index.tsx";
import * as $load from "./routes/load.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $password from "./routes/password.tsx";
import * as $qr from "./routes/qr.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $unit_unitid_ from "./routes/unit/[unitid].tsx";
import * as $App from "./islands/App.tsx";
import * as $HammerScenarioIsland from "./islands/HammerScenarioIsland.tsx";
import * as $LoadIsland from "./islands/LoadIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/api/data/armies-for-user.ts": $api_data_armies_for_user,
    "./routes/api/data/armies/[aid].ts": $api_data_armies_aid_,
    "./routes/api/login.ts": $api_login,
    "./routes/api/signup.ts": $api_signup,
    "./routes/export.tsx": $export,
    "./routes/hammer.tsx": $hammer,
    "./routes/hello.tsx": $hello,
    "./routes/index.tsx": $index,
    "./routes/load.tsx": $load,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/password.tsx": $password,
    "./routes/qr.tsx": $qr,
    "./routes/signup.tsx": $signup,
    "./routes/unit/[unitid].tsx": $unit_unitid_,
  },
  islands: {
    "./islands/App.tsx": $App,
    "./islands/HammerScenarioIsland.tsx": $HammerScenarioIsland,
    "./islands/LoadIsland.tsx": $LoadIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
