// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $export from "./routes/export.tsx";
import * as $hammer from "./routes/hammer.tsx";
import * as $index from "./routes/index.tsx";
import * as $load from "./routes/load.tsx";
import * as $unit_unitid_ from "./routes/unit/[unitid].tsx";
import * as $App from "./islands/App.tsx";
import * as $HammerScenarioIsland from "./islands/HammerScenarioIsland.tsx";
import * as $LoadIsland from "./islands/LoadIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/export.tsx": $export,
    "./routes/hammer.tsx": $hammer,
    "./routes/index.tsx": $index,
    "./routes/load.tsx": $load,
    "./routes/unit/[unitid].tsx": $unit_unitid_,
  },
  islands: {
    "./islands/App.tsx": $App,
    "./islands/HammerScenarioIsland.tsx": $HammerScenarioIsland,
    "./islands/LoadIsland.tsx": $LoadIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
